root: true

extends:
  - '@form8ion'
  - '@form8ion/vitest'
  - '@form8ion/cucumber'

parserOptions:
  ecmaVersion: 2022

rules:
  import/no-unresolved:
    - error
    - ignore:
        - '@octokit/core'
        - 'vitest-when'
        - 'vitest/config'
